# SPDX-License-Identifier: MIT
# Copyright (c) 2026 EoS Project

"""The configure-time gate on the compiled-in trust anchor.

core/keystore.c falls back to a compiled-in public key on a board without
OTP -- every board under boards/ today. Without EBLDR_PRODUCTION_KEY that key
is the RFC 8032 test key, whose secret is published. These tests run real
CMake configures against the repository and pin what the gate does:

  * a Release build of a real board refuses to configure without a key,
    and says why, before anything else goes wrong;
  * EBLDR_ALLOW_DEV_KEY=ON is the one way past that, and it is explicit;
  * the development key and a malformed value are refused as production keys;
  * a real key produces the generated translation unit with those bytes.

Configure only; nothing is compiled.
"""

import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

# RFC 8032 section 7.1 TEST 2 public key: a real curve point that is not the
# development key.
GOOD_KEY = "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c"
# RFC 8032 section 7.1 TEST 1 public key: core/keystore.c's fallback.
DEV_KEY = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"

GATE_MESSAGE = "EBLDR_PRODUCTION_KEY is not set"

pytestmark = pytest.mark.skipif(
    shutil.which("cmake") is None, reason="cmake is not on PATH")


def configure(*defs):
    build = Path(tempfile.mkdtemp(prefix="eboot-gate-"))
    try:
        result = subprocess.run(
            ["cmake", "-S", str(REPO_ROOT), "-B", str(build), *defs],
            capture_output=True, text=True)
        generated = build / "generated" / "production_key.c"
        text = generated.read_text() if generated.exists() else None
        return result, text
    finally:
        shutil.rmtree(build, ignore_errors=True)


def first_error(stderr):
    """The first 'CMake Error' block, so ordering can be asserted."""
    blocks = re.split(r"(?=CMake Error)", stderr)
    return next((b for b in blocks if b.startswith("CMake Error")), "")


def test_release_board_build_refuses_without_a_key():
    result, _ = configure("-DCMAKE_BUILD_TYPE=Release", "-DEBLDR_BOARD=stm32f4")
    assert result.returncode != 0
    assert GATE_MESSAGE in result.stderr
    # The gate, not a missing toolchain or a board port, is what stops it.
    assert GATE_MESSAGE in first_error(result.stderr), result.stderr


def test_release_board_build_can_say_it_is_not_a_release():
    result, _ = configure("-DCMAKE_BUILD_TYPE=Release", "-DEBLDR_BOARD=stm32f4",
                          "-DEBLDR_ALLOW_DEV_KEY=ON")
    assert GATE_MESSAGE not in result.stderr


def test_debug_board_build_and_host_build_are_not_gated():
    # Neither is release-shaped: no key, no opt-out, no gate message.
    result, _ = configure("-DCMAKE_BUILD_TYPE=Debug", "-DEBLDR_BOARD=stm32f4")
    assert GATE_MESSAGE not in result.stderr
    result, generated = configure("-DCMAKE_BUILD_TYPE=Release")
    assert result.returncode == 0, result.stderr
    assert GATE_MESSAGE not in result.stderr
    assert generated is None, "no key was given, so nothing should be generated"


def test_development_key_is_refused_as_a_production_key():
    for spelling in (DEV_KEY, DEV_KEY.upper()):
        result, generated = configure("-DEBLDR_PRODUCTION_KEY=" + spelling)
        assert result.returncode != 0
        assert "development key" in result.stderr, result.stderr
        assert generated is None


@pytest.mark.parametrize("bad", ["abc", GOOD_KEY[:-2], GOOD_KEY + "00",
                                 "zz" + GOOD_KEY[2:]])
def test_malformed_key_is_refused(bad):
    result, generated = configure("-DEBLDR_PRODUCTION_KEY=" + bad)
    assert result.returncode != 0
    assert "exactly 64" in result.stderr, result.stderr
    assert generated is None


def test_real_key_generates_the_anchor_source():
    result, generated = configure("-DCMAKE_BUILD_TYPE=Release",
                                  "-DEBLDR_BOARD=stm32f4",
                                  "-DEBLDR_PRODUCTION_KEY=" + GOOD_KEY.upper())
    assert GATE_MESSAGE not in result.stderr
    assert generated is not None, result.stderr
    assert "ebldr_production_key[EOS_ED25519_PUB_KEY_SIZE]" in generated
    emitted = "".join(re.findall(r"0x([0-9a-f]{2})", generated))
    assert emitted == GOOD_KEY, "the generated bytes must be the configured key"
